In [38]:
import pandas as pd
import numpy as np

from sklearn.datasets import fetch_openml
#import mathplotlib.pyplot as plt
#%pip install 

In [39]:
# grabing entire(70,000) mnist dataset putting into numpy array
mnist = fetch_openml('mnist_784', version=1, as_frame=False, parser='auto')

In [40]:
# setting up features for training
x = mnist.data

In [41]:
# setting up targets
y = mnist.target

In [44]:
#print(mnist.DESCR)

In [45]:
print(mnist.data)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
